# Form implementation generated from reading ui file 'c:\Users\PC\CalculadoraGUI\maindisenio.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(294, 369)
        MainWindow.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_mas = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_mas.setGeometry(QtCore.QRect(220, 250, 61, 41))
        self.pushButton_mas.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"font: 12pt \"Arial\";\n"
"color: white;")
        self.pushButton_mas.setObjectName("pushButton_mas")
        self.pushButton_seis = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_seis.setGeometry(QtCore.QRect(150, 250, 61, 41))
        self.pushButton_seis.setStyleSheet("background-color: rgb(153, 153, 153);\n"
"font: 12pt \"Arial\";\n"
"color: white;")
        self.pushButton_seis.setObjectName("pushButton_seis")
        self.pushButton_cinco = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_cinco.setGeometry(QtCore.QRect(80, 200, 61, 41))
        self.pushButton_cinco.setStyleSheet("background-color: rgb(153, 153, 153);\n"
"font: 12pt \"Arial\";\n"
"color: white;")
        self.pushButton_cinco.setObjectName("pushButton_cinco")
        self.pushButton_AC = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_AC.setGeometry(QtCore.QRect(10, 100, 61, 41))
        self.pushButton_AC.setStyleSheet("background-color: rgb(79, 79, 79);\n"
"font: 12pt \"Arial\";\n"
"color: white;")
        self.pushButton_AC.setObjectName("pushButton_AC")
        self.pushButton_dos = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_dos.setGeometry(QtCore.QRect(80, 250, 61, 41))
        self.pushButton_dos.setStyleSheet("background-color: rgb(153, 153, 153);\n"
"font: 12pt \"Arial\";\n"
"color: white;")
        self.pushButton_dos.setObjectName("pushButton_dos")
        self.pushButton_menos = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_menos.setGeometry(QtCore.QRect(220, 200, 61, 41))
        self.pushButton_menos.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"font: 12pt \"Arial\";\n"
"color: white;")
        self.pushButton_menos.setObjectName("pushButton_menos")
        self.pushButton_cuatro = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_cuatro.setGeometry(QtCore.QRect(10, 200, 61, 41))
        self.pushButton_cuatro.setStyleSheet("background-color: rgb(153, 153, 153);\n"
"font: 12pt \"Arial\";\n"
"color: white;")
        self.pushButton_cuatro.setObjectName("pushButton_cuatro")
        self.pushButton_tres = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_tres.setGeometry(QtCore.QRect(150, 200, 61, 41))
        self.pushButton_tres.setStyleSheet("background-color: rgb(153, 153, 153);\n"
"font: 12pt \"Arial\";\n"
"color: white;")
        self.pushButton_tres.setObjectName("pushButton_tres")
        self.pushButton_dividir = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_dividir.setGeometry(QtCore.QRect(220, 100, 61, 41))
        self.pushButton_dividir.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"font: 12pt \"Arial\";\n"
"color: white;")
        self.pushButton_dividir.setObjectName("pushButton_dividir")
        self.pushButton_nueve = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_nueve.setGeometry(QtCore.QRect(150, 150, 61, 41))
        self.pushButton_nueve.setStyleSheet("background-color: rgb(153, 153, 153);\n"
"font: 12pt \"Arial\";\n"
"color: white;")
        self.pushButton_nueve.setObjectName("pushButton_nueve")
        self.pushButton_siete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_siete.setGeometry(QtCore.QRect(10, 150, 61, 41))
        self.pushButton_siete.setStyleSheet("background-color: rgb(153, 153, 153);\n"
"font: 12pt \"Arial\";\n"
"color: white;")
        self.pushButton_siete.setObjectName("pushButton_siete")
        self.pushButton_ocho = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_ocho.setGeometry(QtCore.QRect(80, 150, 61, 41))
        self.pushButton_ocho.setStyleSheet("background-color: rgb(153, 153, 153);\n"
"font: 12pt \"Arial\";\n"
"color: white;")
        self.pushButton_ocho.setObjectName("pushButton_ocho")
        self.pushButton_punto = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_punto.setGeometry(QtCore.QRect(150, 300, 61, 41))
        self.pushButton_punto.setStyleSheet("background-color: rgb(153, 153, 153);\n"
"font: 12pt \"Arial\";\n"
"color: white;")
        self.pushButton_punto.setObjectName("pushButton_punto")
        self.pushButton_PosNeg = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_PosNeg.setGeometry(QtCore.QRect(80, 100, 61, 41))
        self.pushButton_PosNeg.setStyleSheet("background-color: rgb(79, 79, 79);\n"
"font: 12pt \"Arial\";\n"
"color: white;")
        self.pushButton_PosNeg.setObjectName("pushButton_PosNeg")
        self.pushButton_multipli = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_multipli.setGeometry(QtCore.QRect(220, 150, 61, 41))
        self.pushButton_multipli.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"font: 12pt \"Arial\";\n"
"color: white;")
        self.pushButton_multipli.setObjectName("pushButton_multipli")
        self.pushButton_cero = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_cero.setGeometry(QtCore.QRect(10, 300, 131, 41))
        self.pushButton_cero.setStyleSheet("background-color: rgb(153, 153, 153);\n"
"font: 12pt \"Arial\";\n"
"color: white;")
        self.pushButton_cero.setObjectName("pushButton_cero")
        self.pushButton_igual = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_igual.setGeometry(QtCore.QRect(220, 300, 61, 41))
        self.pushButton_igual.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(12, 12, 12);\n"
"font: 12pt \"Arial\";\n"
"color: white;\n"
"")
        self.pushButton_igual.setObjectName("pushButton_igual")
        self.pushButton_porcentaje = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_porcentaje.setGeometry(QtCore.QRect(150, 100, 61, 41))
        self.pushButton_porcentaje.setStyleSheet("background-color: rgb(79, 79, 79);\n"
"font: 12pt \"Arial\";\n"
"color: white;")
        self.pushButton_porcentaje.setObjectName("pushButton_porcentaje")
        self.pushButton_uno = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_uno.setGeometry(QtCore.QRect(10, 250, 61, 41))
        self.pushButton_uno.setStyleSheet("background-color: rgb(153, 153, 153);\n"
"font: 12pt \"Arial\";\n"
"color: white;")
        self.pushButton_uno.setObjectName("pushButton_uno")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 15, 271, 31))
        self.label.setStyleSheet("font: 22pt \"Arial\";\n"
"color: white;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 60, 131, 31))
        self.label_2.setStyleSheet("font: 22pt \"Arial\";\n"
"color: white;\n"
"")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_mas.setText(_translate("MainWindow", "+"))
        self.pushButton_seis.setText(_translate("MainWindow", "6"))
        self.pushButton_cinco.setText(_translate("MainWindow", "5"))
        self.pushButton_AC.setText(_translate("MainWindow", "AC"))
        self.pushButton_dos.setText(_translate("MainWindow", "2"))
        self.pushButton_menos.setText(_translate("MainWindow", "-"))
        self.pushButton_cuatro.setText(_translate("MainWindow", "4"))
        self.pushButton_tres.setText(_translate("MainWindow", "3"))
        self.pushButton_dividir.setText(_translate("MainWindow", "/"))
        self.pushButton_nueve.setText(_translate("MainWindow", "9"))
        self.pushButton_siete.setText(_translate("MainWindow", "7"))
        self.pushButton_ocho.setText(_translate("MainWindow", "8"))
        self.pushButton_punto.setText(_translate("MainWindow", "."))
        self.pushButton_PosNeg.setText(_translate("MainWindow", "+/-"))
        self.pushButton_multipli.setText(_translate("MainWindow", "*"))
        self.pushButton_cero.setText(_translate("MainWindow", "0"))
        self.pushButton_igual.setText(_translate("MainWindow", "="))
        self.pushButton_porcentaje.setText(_translate("MainWindow", "%"))
        self.pushButton_uno.setText(_translate("MainWindow", "1"))
        self.label_2.setText(_translate("MainWindow", "       0"))
